development: &default
  adapter: postgresql
  encoding: unicode
  database: stock_database_development
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: stock_database_test